import gc3AssociationReportTypeContactTypeCriteriaStructure from './association_report_type_contact_type';
import gc3AssociationReportTypeFieldCriteriaStructure from './association_report_type_field';
import gc3TargetAudienceCriteriaStructure from './target_audience';

export {
	gc3AssociationReportTypeContactTypeCriteriaStructure,
	gc3AssociationReportTypeFieldCriteriaStructure,
	gc3TargetAudienceCriteriaStructure
};
